Repository wecode-bootcamp-korea/17-2nd-OurRealTrip-frontend, pull requests merged in 2021-03, with the labels that each got.

#1 [17기 이정민] 초기세팅 재 수정완료 (Nav, Footer 기본 클래스컴포넌트 생성/theme.js 수정)
  package-lock.json
  package.json
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/Airline/Airline.js
  src/Routes.js
  src/Styles/globalStyles.js
  src/Styles/theme.js
  src/index.js
Labels: Status: 리뷰 요청

#4 [17기 박경토] Footer 최종리뷰수정완료
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/Airline/Airline.js
Labels: Status: 리뷰 요청

#10 [17기 이정민] theme 파일 작성 완료
  src/Styles/theme.js
Labels: Status: Accepted

#9 [17기 이정민] Navbar 파일 한개로 통합 완료 (Footer부분 수정완료)
  package-lock.json
  package.json
  public/images/airline1.jpg
  public/images/ourrealtrip.png
  public/images/ourrealtrip1.png
  public/images/staymain1.jpg
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Pages/SignIn/SignIn.js
  src/Routes.js
Labels: Status: 수정 요청

#11 [17기 이정민] 카카오 로그인 구현 완료
  public/index.html
  src/Components/Nav/Nav.js
  src/Pages/SignIn/SignIn.js
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: Accepted

#5 [17기 이정민] Stay 리스트 페이지 다중체크박스 필터 부분 구현중
  public/data/stayListData.json
  src/Components/Nav/Nav.js
  src/Pages/Stay/StayList/Components/StayCardList.js
  src/Pages/Stay/StayList/Components/StayListFilterData.js
  src/Pages/Stay/StayList/Components/StayListHeader.js
  src/Pages/Stay/StayList/Components/StayPagination.js
  src/Pages/Stay/StayList/StayList.js
  src/Pages/Stay/StayMain/Components/SearchContainer.js
  src/Routes.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#7 [17기 곽진석] 리뷰내용 수정 및 추가구현 진행중
  public/data/ticketData.json
  public/images/airline1.jpeg
  public/images/background.jpeg
  src/Pages/Airline/AirlineList/AirlineList.js
  src/Pages/Airline/AirlineList/AirlineListSearchBox/AirlineListSearchBox.js
  src/Pages/Airline/AirlineList/AirlineListSearchBox/Input.js
  src/Pages/Airline/AirlineList/AirlineListSearchBox/MainSearchArea.js
  src/Pages/Airline/AirlineList/AirlineListSearchBox/TripType.js
  src/Pages/Airline/AirlineList/AirlineSelectedBox/AirlineSelectedBox.js
  src/Pages/Airline/AirlineList/AirlineSelectedBox/AirlineTime.js
  src/Pages/Airline/AirlineList/AirlineSelectedBox/SendFilter.js
  src/Pages/Airline/AirlineList/Components/FilterCategoryInSideBar.js
  src/Pages/Airline/AirlineList/LodingPage/LodingAnimation.js
  src/Pages/Airline/AirlineList/LodingPage/LodingPage.js
  src/Pages/Airline/AirlineList/LodingPage/LodingPageMain.js
  src/Pages/Airline/AirlineList/LodingPage/TowhereBox.js
  src/Pages/Airline/AirlineList/LodingPage/plane.mp4
  src/Pages/Airline/AirlineList/ReservationBox/DATAINBOX.js
  src/Pages/Airline/AirlineList/ReservationBox/ReservationBox.js
  src/Pages/Airline/AirlineList/TicketInList/PlaneTime.js
  src/Pages/Airline/AirlineList/TicketInList/Ticket.js
  src/Pages/Airline/AirlineList/TicketInList/TicketInList.js
  src/Pages/Airline/MainSearchArea/Input.js
Labels: Status: Accepted
